In [1]:
import pandas as pd

In [32]:
visit_tour = pd.read_csv('../../data/jeju_tour_places_modified.csv')

In [33]:
visit_tour

alltag            contentsid  \
0                                   휴식/힐링,체험관광,액티비티,사계절  CNTS_200000000012469   
1     부모,커플,친구,경관/포토,휴식/힐링,테마공원,오름,사계절,청년,중/장년,휴식/치유...  CNTS_200000000009501   
2     커플,부모,혼자,친구,아이,맑음,흐림,비.눈,경관/포토,휴식/힐링,미술/박물관,사계...  CNTS_200000000012075   
3                                                   관광지  CNTS_200000000013590   
4                  실내,문화유적지,가을,문화관광,역사유적,어트랙션,공용주차장,어려움  CNTS_000000000021292   
...                                                 ...                   ...   
1098  해변,경관/포토,커플,맑음,여름,공용주차장,화장실,음료대,유도 및 안내시설,경보 및...  CONT_000000000500682   
1099                         커플,친구,아이,부모,혼자,경관/포토,여름,맑음  CNTS_000000000018385   
1100                                       체험관광,아이,맑음,봄  CNTS_000000000020230   
1101  승마,액티비티,친구,커플,공용주차장,현금결제,카드결제,화장실,무료 WIFI,음료대,...  CONT_000000000500560   
1102  섬속의섬,일몰,휴식/힐링,아이,맑음,여름,공용주차장,현금결제,카드결제,화장실,편의점...  CONT_000000000500267   

     contentscd             title                      address  \
0           관광지  제로스테이션(제로포인트트레일)      제주특별자치도 제주시 건입동 1136 2층   
1           관광지         궁대오름(궁대악)  제주특별자치도 서귀포시 성산읍 수산리 4711-1   
2           관광지        헌마공신김만일기념관             서귀포시 남원읍 서성로 919   
3           관광지              본초족욕          제주특별자치도 제주시 연동 1326   
4           관광지             강병대교회    제주특별자치도 서귀포시 대정읍 상모리 3846   
...         ...               ...                          ...   
1098        관광지              한담해변   제주특별자치도 제주시 애월읍 애월리 2533-1   
1099        관광지         김경숙해바라기농장          제주특별자치도 제주시 회천동 391   
1100        관광지            아침미소목장          제주특별자치도 제주시 월평동 155   
1101        관광지            제주승마공원   제주특별자치도 제주시 애월읍 녹고메길 152-1   
1102        관광지               비양도          제주특별자치도 제주시 한림읍 협재리   

                      roadaddress  \
0           제주특별자치도 제주시 산지로 25 2층   
1       제주특별자치도 서귀포시 성산읍 금백조로 446   
2                서귀포시 남원읍 서성로 919   
3              제주특별자치도 제주시 은수길 65   
4     제주특별자치도 서귀포시 대정읍 상모대서로 43-3   
...                           ...   
1098   제주특별자치도 제주시 애월읍 애월로1길 26-4   
1099        제주특별자치도 제주시 번영로 854-1   
1100      제주특별자치도 제주시 첨단동길 160-20   
1101   제주특별자치도 제주시 애월읍 녹고메길 152-1   
1102          제주특별자치도 제주시 한림읍 협재리   

                                                    tag  \
0                     휴식/힐링,체험관광,액티비티,사계절,체험,레저/체험,어트랙션   
1     부모,커플,친구,경관/포토,휴식/힐링,테마공원,오름,사계절,청년,중/장년,휴식/치유...   
2     커플,부모,혼자,친구,아이,맑음,흐림,비.눈,경관/포토,휴식/힐링,미술/박물관,사계...   
3                                관광지,안전여행스탬프,experience   
4                            실내,문화유적지,가을,문화관광,역사유적,어트랙션   
...                                                 ...   
1098                 해변,경관/포토,커플,맑음,여름,자연경관,포토스팟,봄꽃,유채꽃   
1099  커플,친구,아이,부모,혼자,경관/포토,여름,맑음,자연경관,포토스팟,어린이,어트랙션,...   
1100                           체험관광,아이,맑음,봄,체험,어린이,어트랙션   
1101                        승마,액티비티,친구,커플,체험,레저/체험,어트랙션   
1102           섬속의섬,일몰,휴식/힐링,아이,맑음,여름,자연경관,어린이,언택트,유네스코   

                                           introduction  readcnt  likecnt  \
0     제로스테이션은 산지천에 위치한 카페이자 길과 여행을 사랑하는 사람들을 위한 공간이다...      530        0   
1     오름의 모양새가 마치 활처럼 생기고, 오름 허리에 활(궁·弓)자 모양의 띠가 둘러져...     1723        0   
2     임진왜란 당시 전쟁에 사용할 말 500마리를 헌납하면서 국난극복에 기여한 김만일(1...      323        2   
3                 천연 족욕 테라피를 즐기면서 심신의 피로를 확 날려버릴 수 있는 곳       40        1   
4                                   우리나라에서 가장 오래된 군인 교회     2839        0   
...                                                 ...      ...      ...   
1098                         해안길을 따라 산책할 수 있는 제주의 숨은 비경    27040        9   
1099                           노란 물결의 해바라기가 펼쳐진 해바라기 농장    67183       17   
1100  제주시 근교에 자리한 아침미소목장은 건강한 젖소들이 자라는 친환경 목장이다. 넓은 ...    66282       38   
1101    국내최대 외승,트래킹/ 국내 최초 야외 야간 승마 및 전문 승마체험 및 회원제 승마장    20606        2   
1102  천 년의 시간을 간직한 섬\r\n· 천연기념물 제439호\r\n· 제주도기념물 제4...    44298        7   

      ...  evelpt   latitude   longitude        phoneno  \
0     ...     0.0  33.514733  126.529280   064-702-1947   
1     ...     0.0  33.440562  126.822089   064-787-4711   
2     ...     0.0        Na

In [98]:
import re
def extract_word(text):
    hangul = re.compile('[^가-힣 | 0-9 | a-z]') 
    result = hangul.sub(' ', text) 
    return result

In [59]:
import numpy as np
from numpy import dot
from numpy.linalg import norm

def cos_sim(A, B):
  return dot(A, B)/(norm(A)*norm(B))


In [40]:
from konlpy.tag import Okt
okt = Okt()

In [99]:
test_text=visit_tour['tag'].apply(lambda x: extract_word(x))

In [100]:
test_text[3]

'관광지 안전여행스탬프 experience'

In [101]:
t1=test_text.apply(lambda x: x.split(' '))

In [102]:
t1

0             [휴식, 힐링, 체험관광, 액티비티, 사계절, 체험, 레저, 체험, 어트랙션]
1       [부모, 커플, 친구, 경관, 포토, 휴식, 힐링, 테마공원, 오름, 사계절, 청년...
2       [커플, 부모, 혼자, 친구, 아이, 맑음, 흐림, 비, 눈, 경관, 포토, 휴식,...
3                              [관광지, 안전여행스탬프, experience]
4                       [실내, 문화유적지, 가을, 문화관광, 역사유적, 어트랙션]
                              ...                        
1098        [해변, 경관, 포토, 커플, 맑음, 여름, 자연경관, 포토스팟, 봄꽃, 유채꽃]
1099    [커플, 친구, 아이, 부모, 혼자, 경관, 포토, 여름, 맑음, 자연경관, 포토스...
1100                     [체험관광, 아이, 맑음, 봄, 체험, 어린이, 어트랙션]
1101                 [승마, 액티비티, 친구, 커플, 체험, 레저, 체험, 어트랙션]
1102    [섬속의섬, 일몰, 휴식, 힐링, 아이, 맑음, 여름, 자연경관, 어린이, 언택트,...
Name: tag, Length: 1103, dtype: object

In [49]:
test_lst=test_text.to_list()

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

In [60]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity



In [51]:
count_vec = CountVectorizer()
m = count_vec.fit_transform(test_lst)
m.toarray()

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [86]:
count_vec.vocabulary_

{'휴식': 353,
 '힐링': 358,
 '체험관광': 276,
 '액티비티': 191,
 '사계절': 126,
 '체험': 275,
 '레저': 78,
 '어트랙션': 195,
 '부모': 118,
 '커플': 293,
 '친구': 284,
 '경관': 15,
 '포토': 318,
 '테마공원': 305,
 '오름': 209,
 '청년': 273,
 '장년': 241,
 '치유': 282,
 '자연경관': 238,
 '도보여행': 57,
 '도보': 56,
 '포토스팟': 319,
 '혼자': 347,
 '아이': 184,
 '맑음': 87,
 '흐림': 356,
 '미술': 104,
 '박물관': 110,
 '노년': 44,
 '전시와': 246,
 '행사': 342,
 '실내관광지': 178,
 '역사유적': 202,
 '어린이': 193,
 '관광지': 31,
 '안전여행스탬프': 187,
 '실내': 177,
 '문화유적지': 99,
 '가을': 1,
 '문화관광': 98,
 '포구': 317,
 '해변': 334,
 '겨울': 13,
 '제주4': 250,
 '걷기': 12,
 '등산': 70,
 '여름': 199,
 '수국': 153,
 '언택트': 197,
 '지질공원': 266,
 '유네스코': 226,
 '휴양림': 354,
 '캠핑장': 292,
 '야영장': 192,
 '캠핑': 291,
 '단풍': 54,
 '숙소': 161,
 '휴양펜션': 355,
 '펜션': 316,
 '독채': 59,
 '한옥': 329,
 '온돌방': 212,
 '바비큐': 109,
 '수영장': 158,
 '공공와이파이존': 20,
 '요가': 216,
 '카페': 287,
 '음식': 231,
 '디저트': 71,
 '웰니스': 225,
 '미술관': 105,
 '제주풍경': 258,
 '화방': 348,
 '예술': 208,
 '일출': 236,
 '숲길': 162,
 '곶자왈': 26,
 '용천수': 218,
 '물놀이': 101,
 '테마파크': 3

In [103]:
count_vec1 = CountVectorizer(tokenizer=lambda x: x,lowercase=False)
m1 = count_vec1.fit_transform(t1)
m1.toarray()

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]], dtype=int64)

In [104]:
arr2 = m1.toarray()

In [105]:
count_vec1.vocabulary_

{'휴식': 374,
 '힐링': 379,
 '체험관광': 297,
 '액티비티': 209,
 '사계절': 140,
 '체험': 296,
 '레저': 88,
 '어트랙션': 213,
 '부모': 130,
 '커플': 314,
 '친구': 305,
 '경관': 22,
 '포토': 339,
 '테마공원': 326,
 '오름': 227,
 '청년': 294,
 '중': 283,
 '장년': 259,
 '치유': 303,
 '자연경관': 256,
 '도보여행': 67,
 '도보': 66,
 '포토스팟': 340,
 '혼자': 368,
 '아이': 202,
 '맑음': 97,
 '흐림': 377,
 '비': 135,
 '눈': 58,
 '미술': 114,
 '박물관': 120,
 '노년': 53,
 '전시와': 264,
 '행사': 363,
 '실내관광지': 196,
 '역사유적': 220,
 '어린이': 211,
 '관광지': 38,
 '안전여행스탬프': 205,
 'experience': 5,
 '실내': 195,
 '문화유적지': 109,
 '가을': 8,
 '문화관광': 108,
 '포구': 338,
 '해변': 355,
 '겨울': 20,
 '4': 2,
 '3': 1,
 '제주4': 269,
 '산': 144,
 '걷기': 19,
 '등산': 80,
 '여름': 217,
 '수국': 169,
 '언택트': 215,
 '지질공원': 286,
 '유네스코': 244,
 '휴양림': 375,
 '캠핑장': 313,
 '야영장': 210,
 '캠핑': 312,
 '단풍': 64,
 '숙소': 177,
 '휴양펜션': 376,
 '펜션': 337,
 '독채': 69,
 '한옥': 350,
 '온돌방': 230,
 '바비큐': 119,
 '수영장': 174,
 '공공와이파이존': 27,
 '요가': 234,
 '카페': 308,
 '음식': 249,
 '디저트': 81,
 '웰니스': 243,
 '미술관': 115,
 '제주풍경': 277,
 '화방': 369,
 '예

In [61]:
arr.shape

(1103, 360)

In [57]:
arr[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [62]:
cosine_sim = cosine_similarity(arr, arr)
print('코사인 유사도 연산 결과 :',cosine_sim.shape)

코사인 유사도 연산 결과 : (1103, 1103)


In [106]:
cosine_sim2 = cosine_similarity(arr2, arr2)
print('코사인 유사도 연산 결과 :',cosine_sim2.shape)

코사인 유사도 연산 결과 : (1103, 1103)


In [72]:
title_to_index = dict(zip(visit_tour['title'], visit_tour.index))

# 영화 제목 Father of the Bride Part II의 인덱스를 리턴
idx = title_to_index['협재해수욕장']
print(idx)

1047


In [107]:
def get_recommendations(title, cosine_sim=cosine_sim2):
    # 선택한 영화의 타이틀로부터 해당 영화의 인덱스를 받아온다.
    idx = title_to_index[title]

    # 해당 영화와 모든 영화와의 유사도를 가져온다.
    sim_scores = list(enumerate(cosine_sim[idx]))

    # 유사도에 따라 영화들을 정렬한다.
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # 가장 유사한 10개의 영화를 받아온다.
    sim_scores = sim_scores[1:11]

    # 가장 유사한 10개의 영화의 인덱스를 얻는다.
    tour_indices = [idx[0] for idx in sim_scores]

    # 가장 유사한 10개의 영화의 제목을 리턴한다.
    return visit_tour['title'].iloc[tour_indices]

In [108]:
get_recommendations('협재해수욕장')

1074            곽지해수욕장
1078            금능해수욕장
1059            김녕해수욕장
1092            함덕해수욕장
1079         화순금모래해수욕장
263           중문색달해수욕장
789               하도해변
884           신양섭지해수욕장
1076            표선해수욕장
271     화순금모래해수욕장담수수영장
Name: title, dtype: object

In [69]:
title_to_index['협재해수욕장']

1177